version: '2'
services:
    web:
        build: www
        links:
        - api
        ports:
        - "80:80"
    api:
        build: server
        ports:
        - "5000:5000"

volumes:
    certs:

