version: '2'
services:
    web:
        build: www
        ports:
        - "80:80"
    api:
        build: server
        ports:
        - "5000:5000"
        links:
        - postgres
    postgres:
        image: mdillon/postgis
        environment:
        - PGDATA=/var/lib/postgresql/data/data/
        - POSTGRES_PASSWORD=Best2livemaps
        volumes:
        - data:/var/lib/postgresql/data/data/

volumes:
    data:

